tunnel: c4d13e7c-07a4-49be-b7c9-938de3a75ec8
credentials-file: C:\Users\lukas\.cloudflared\c4d13e7c-07a4-49be-b7c9-938de3a75ec8.json
originRequest:
  noTLSVerify: false

ingress:
  - hostname: arkuszowniasmb.pl
    service: http://localhost:80
  - hostname: www.arkuszowniasmb.pl
    service: http://localhost:80
  - service: http_status:404

