tunnel: 9320212e-f379-4261-8777-f9623823beee
credentials-file: C:\Users\lukas\.cloudflared\9320212e-f379-4261-8777-f9623823beee.json
originRequest:
  noTLSVerify: true
  connectTimeout: 30s
  tcpKeepAlive: 30s

ingress:
  - hostname: arkuszowniasmb.pl
    service: http://127.0.0.1:80
  - hostname: www.arkuszowniasmb.pl
    service: http://127.0.0.1:80
  - service: http_status:404

