tunnel: 3e14f36a-7e9c-4a54-92ea-a58f1e856df5
credentials-file: C:\Users\lukas\.cloudflared\3e14f36a-7e9c-4a54-92ea-a58f1e856df5.json
originRequest:
  noTLSVerify: false

ingress:
  - hostname: arkuszowniasmb.pl
    service: http://localhost:80
  - hostname: www.arkuszowniasmb.pl
    service: http://localhost:80
  - service: http_status:404

