tunnel-token: eyJhIjoiMWQzYWI2ZDU4ZjZkZjQ1NTEwMTlkOTZhMTQ3MmJkNGIiLCJ0IjoiODg2MGUwMzEtODUxYi00N2U2LThkYjctNjY1YjFhZjQwZjQzIiwicyI6Ik1UY3hOelZsTVRBdE1tVXdPUzAwTldWbExXRTBOakV0TkRsaVltUmpORFUzWldNMiJ9
logfile: ./logs/cloudflared-pl.log
loglevel: info
protocol: http2

ingress:
  - hostname: arkuszowniasmb.pl
    service: http://192.168.10.147:8088
  - hostname: www.arkuszowniasmb.pl
    service: http://192.168.10.147:8088
  - service: http_status:404
