tunnel: arkuszownia-local
credentials-file: C:\Users\lukas\PyCharmMiscProject\.cloudflared\cert.json

ingress:
  - hostname: arkuszowniasmb.pl
    service: http://localhost:8088
  - hostname: www.arkuszowniasmb.pl
    service: http://localhost:8088
  - hostname: api.arkuszowniasmb.pl
    service: http://localhost:8088
  - service: http_status:404
